{{ config(materialized = 'view') }}


WITH base AS (
  SELECT CURRENCY, 
  ADSET_BID_STRATEGY AS CAMPAIGN_TYPE, 
  ADSET_ID AS CAMPAIGN_ID, 
  ADSET_NAME AS CAMPAIGN_NAME, 
  ADSET_STATUS AS CAMPAIGN_STATUS, 
  ADVERTISER_ID AS ACCOUNT_ID, 
  ADVERTISER_NAME AS ACCOUNT_NAME, 
  DATE, 
  CLICKS, 
  COST, 
  IMPRESSIONS
  FROM {{var('paid_media_reporting__supermetrics_schema')}}.CRI_BASE
),
reach AS (
  SELECT ADSET_ID AS CAMPAIGN_ID, 
  ADSET_NAME AS CAMPAIGN_NAME, 
  UNIQUE_IMPRESSIONS AS AUDIENCE_SIZE, 
  CAST(UNIQUE_IMPRESSIONS * REACH AS INTEGER) AS REACH
  FROM {{var('paid_media_reporting__supermetrics_schema')}}.CRI_REACH
)
SELECT 
  base.CURRENCY, 
  base.CAMPAIGN_TYPE, 
  base.CAMPAIGN_ID, 
  base.CAMPAIGN_NAME, 
  base.CAMPAIGN_STATUS, 
  base.ACCOUNT_ID, 
  base.ACCOUNT_NAME, 
  base.DATE, 
  base.CLICKS, 
  base.COST, 
  base.IMPRESSIONS, 
  reach.AUDIENCE_SIZE, 
  reach.REACH
FROM base
LEFT JOIN reach
ON base.CAMPAIGN_ID = reach.CAMPAIGN_ID
