{{ config(materialized = 'view') }}

SELECT DATE, ACCOUNT_NAME, CURRENCY, ACCOUNT_ID, CAMPAIGN_NAME, PLATFORM_LEVEL_1, PLATFORM_LEVEL_2, CAMPAIGN_STATUS, CAMPAIGN_TYPE, CAMPAIGN_ID, AD_GROUP_NAME, AD_GROUP_ID, KEYWORD_NAME, KEYWORD_ID, CLICKS, COST, IMPRESSIONS
FROM google_ads
WHERE CAMPAIGN_TYPE = 'Search'
UNION
SELECT DATE, ACCOUNT_NAME, CURRENCY, ACCOUNT_ID, CAMPAIGN_NAME, PLATFORM_LEVEL_1, PLATFORM_LEVEL_2, CAMPAIGN_STATUS, CAMPAIGN_TYPE, CAMPAIGN_ID, AD_GROUP_NAME, AD_GROUP_ID, KEYWORD_NAME, KEYWORD_ID, CLICKS, COST, IMPRESSIONS
FROM bing_ads
UNION
SELECT DATE, ACCOUNT_NAME, CURRENCY, ACCOUNT_ID, CAMPAIGN_NAME, PLATFORM_LEVEL_1, PLATFORM_LEVEL_2, CAMPAIGN_STATUS, CAMPAIGN_TYPE, CAMPAIGN_ID, AD_GROUP_NAME, AD_GROUP_ID, KEYWORD_NAME, KEYWORD_ID, CLICKS, COST, IMPRESSIONS
FROM amazon_ads
WHERE CAMPAIGN_TYPE IS NULL