 {{ config(materialized = 'view') }}

SELECT ACCOUNT_ID, ACCOUNT_NAME, AD_ID, AD_NAME, CAMPAIGN_ID, CAMPAIGN_NAME, AD_GROUP_ID, AD_GROUP_NAME, CAMPAIGN_TYPE, CAMPAIGN_STATUS, CURRENCY, DATE, PLATFORM_LEVEL_1, PLATFORM_LEVEL_2, NULL AS KEYWORD_NAME, NULL AS KEYWORD_ID, CLICKS, COST, IMPRESSIONS, REACH, FREQUENCY
FROM paid_social
union 
select ACCOUNT_ID, ACCOUNT_NAME, AD_ID, AD_NAME, CAMPAIGN_ID, CAMPAIGN_NAME, AD_GROUP_ID, AD_GROUP_NAME, CAMPAIGN_TYPE, CAMPAIGN_STATUS, CURRENCY, DATE, PLATFORM_LEVEL_1, PLATFORM_LEVEL_2, KEYWORD_NAME, KEYWORD_ID, CLICKS, COST, IMPRESSIONS, NULL AS REACH, NULL AS FREQUENCY
from google_ads
WHERE CAMPAIGN_TYPE NOT IN ('Search')
union
SELECT ACCOUNT_ID, ACCOUNT_NAME, AD_ID, AD_NAME, CAMPAIGN_ID, CAMPAIGN_NAME, AD_GROUP_ID, AD_GROUP_NAME, CAMPAIGN_TYPE, CAMPAIGN_STATUS, CURRENCY, DATE, PLATFORM_LEVEL_1, PLATFORM_LEVEL_2, KEYWORD_NAME, KEYWORD_ID, CLICKS, COST, IMPRESSIONS, NULL AS REACH, NULL AS FREQUENCY
FROM amazon_ads
WHERE CAMPAIGN_TYPE = 'sponsoredProducts'
union
select ACCOUNT_ID, ACCOUNT_NAME, NULL AS AD_ID, NULL AS AD_NAME, CAMPAIGN_ID, CAMPAIGN_NAME, NULL AS AD_GROUP_ID, NULL AS AD_GROUP_NAME, CAMPAIGN_TYPE, CAMPAIGN_STATUS, CURRENCY, DATE, NULL AS PLATFORM_LEVEL_1, NULL AS PLATFORM_LEVEL_2, NULL AS KEYWORD_NAME, NULL AS KEYWORD_ID, CLICKS, COST, IMPRESSIONS, REACH, NULL AS FREQUENCY
from criteo_ads