{{ config(materialized = 'view') }}

select ACCOUNT_ID, ACCOUNT_NAME, AD_ID, AD_NAME, CAMPAIGN_ID, CAMPAIGN_NAME, AD_GROUP_ID, AD_GROUP_NAME, CAMPAIGN_TYPE, CAMPAIGN_STATUS, CURRENCY, DATE, PLATFORM_LEVEL_1, PLATFORM_LEVEL_2, CLICKS, COST, IMPRESSIONS, REACH, FREQUENCY
from  SM_TEMPLATES.DBT.TIK_BASE_V2
union 
select ACCOUNT_ID, ACCOUNT_NAME, AD_ID, AD_NAME, CAMPAIGN_ID, CAMPAIGN_NAME, AD_GROUP_ID, AD_GROUP_NAME, CAMPAIGN_TYPE, CAMPAIGN_STATUS, CURRENCY, DATE, PLATFORM_LEVEL_1, PLATFORM_LEVEL_2, CLICKS, COST, IMPRESSIONS, REACH, FREQUENCY
from SM_TEMPLATES.DBT.FBADS_BASE_V2
union 
select ACCOUNT_ID, ACCOUNT_NAME, AD_ID, AD_NAME, CAMPAIGN_ID, CAMPAIGN_NAME, AD_GROUP_ID, AD_GROUP_NAME, CAMPAIGN_TYPE, CAMPAIGN_STATUS, CURRENCY, DATE, PLATFORM_LEVEL_1, PLATFORM_LEVEL_2, CLICKS, COST, IMPRESSIONS, NULL AS REACH, FREQUENCY
from SM_TEMPLATES.DBT.SNAPCHT_BASE_V2
union 
select ACCOUNT_ID, ACCOUNT_NAME, AD_ID, AD_NAME, CAMPAIGN_ID, CAMPAIGN_NAME, AD_GROUP_ID, AD_GROUP_NAME, CAMPAIGN_TYPE, CAMPAIGN_STATUS, CURRENCY, DATE, PLATFORM_LEVEL_1, PLATFORM_LEVEL_2, CLICKS, COST, IMPRESSIONS, REACH, NULL AS FREQUENCY
from SM_TEMPLATES.DBT.LINKEDINADS_BASE_V2
union 
select ACCOUNT_ID, ACCOUNT_NAME, AD_ID, AD_NAME, CAMPAIGN_ID, CAMPAIGN_NAME, AD_GROUP_ID, AD_GROUP_NAME, CAMPAIGN_TYPE, CAMPAIGN_STATUS, CURRENCY, DATE, PLATFORM_LEVEL_1, PLATFORM_LEVEL_2, CLICKS, COST, IMPRESSIONS, NULL AS REACH, FREQUENCY
from SM_TEMPLATES.DBT.PIA_BASE_V2